app:
  name: go-api
  env: dev
  logLevel: debug
logging:
  filePath: logs/app-dev.log
server:
  address: 192.168.200.57
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s
  maxBodyBytes: 1048576
cors:
  allowedOrigins:
    - "http://localhost:3000"
    - "http://localhost:8080"  
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowedHeaders:
    - Authorization
    - Content-Type
  allowCredentials: true
db:
  dsn: "sqlserver://sa:123456@localhost:1433?database=go_api&encrypt=disable"
  maxOpenConns: 25
  maxIdleConns: 25
  connMaxLifetime: 30m
auth:
  jwtSecret: "change-me"
  issuer: "go-api"
  audience: "go-api-clients"
  accessTokenTTL: 15m
  algorithm: HS256
  privateKeyPath: ""
  publicKeyPath: ""
rateLimit:
  rps: 100
